name: 'List directories'
description: 'Get a JSON list of the directories under the specified directory'
inputs:
  path:
    decription: 'Directory to list'
    required: true
outputs:
  directories:
    description: 'A JSON formatted list of directories'
    value: ${{ steps.set-directories.outputs.directories }}
runs:
  using: 'composite'
  steps:
    - run: sudo apt-get update && sudo apt-get install tree jq -y
      shell: bash
    - id: set-directories
      shell: bash
      run: |
        cd ${{ inputs.path }}
        directories=$(sudo tree -J -d -L 1 | sudo jq -c '.[0].contents | map(.name)')
        echo "directories=$directories" >> $GITHUB_OUTPUT